/*
 * gimnasio-html.js
 * -----------------------------------------------------------------------
 * Solo texto: el documento HTML completo del gimnasio (estilos + markup),
 * como string. No tiene lógica ni funciones, así que puede editarse como
 * si fuera un .html suelto. La lógica que lo entrega al juego (por qué es
 * un string y no un archivo aparte, convenciones de los accesorios, etc.)
 * vive en vestuario.js.
 */
(function () {
  'use strict';

  var RL = (window.RL = window.RL || {});

  var ESTILOS_GIMNASIO = [
    '*{box-sizing:border-box;}',
    'body{margin:0;font-family:"Segoe UI",Verdana,Arial,sans-serif;background:#171314;color:#f2e9e4;}',
    '#gimnasio{padding:14px;}',
    '.ring{position:relative;background:radial-gradient(ellipse at center,#3a2a2a 0%,#171314 78%);',
    '  border:6px solid #7a1f1f;border-radius:10px;padding:18px;margin-bottom:16px;}',
    '.cartel{margin:0 0 10px;text-align:center;color:#e8c9a0;font-size:.85em;letter-spacing:.04em;}',
    '.selector-genero{display:flex;gap:14px;justify-content:center;}',
    '.opcion-genero{cursor:pointer;user-select:none;background:#241b1b;border:2px solid #7a1f1f;',
    '  border-radius:8px;padding:16px 22px;text-align:center;color:#f2e9e4;transition:transform .15s,border-color .15s;}',
    '.opcion-genero:hover{border-color:#e05a2b;transform:translateY(-2px);}',
    '.opcion-genero .icono-genero{display:block;font-size:2em;margin-bottom:6px;}',
    '.nombre-opcion{font-weight:600;}',
    '.peleador{position:relative;margin:0 auto;width:180px;min-height:280px;display:none !important;}',
    '.silueta-contenedor{position:relative;width:180px;height:280px;margin:0 auto;',
    '  background:#241b1b;border-radius:8px;overflow:hidden;}',
    '.silueta{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;display:none;}',
    '.silueta.silueta-activa{display:block;}',
    '.silueta-contenedor.sin-imagen::after{content:attr(data-nombre);position:absolute;inset:0;',
    '  display:flex;align-items:center;justify-content:center;text-align:center;padding:10px;',
    '  color:#c9b7ad;font-size:.85em;}',
    '.slot{position:absolute;width:34px;height:34px;border:2px dashed rgba(242,233,228,.35);',
    '  border-radius:50%;display:flex;align-items:center;justify-content:center;}',
    '.slot img{width:100%;height:100%;object-fit:contain;border-radius:50%;}',
    '.slot.slot-lleno{border-style:solid;border-color:#e05a2b;background:rgba(224,90,43,.15);}',
    '.slot.slot-pop{animation:rl-pop .32s ease;}',
    '@keyframes rl-pop{0%{transform:scale(.35);}60%{transform:scale(1.28);}100%{transform:scale(1);}}',
    '.slot[data-slot="casco"]{top:2px;left:73px;width:44px;height:44px;}',
    '.slot[data-slot="bucal"]{top:40px;left:83px;width:24px;height:24px;}',
    '.slot[data-slot="venda-izq"]{top:118px;left:18px;}',
    '.slot[data-slot="venda-der"]{top:118px;left:128px;}',
    '.slot[data-slot="guante-izq"]{top:150px;left:6px;}',
    '.slot[data-slot="guante-der"]{top:150px;left:140px;}',
    '.slot[data-slot="short"]{top:190px;left:73px;width:44px;height:34px;border-radius:8px;}',
    '.slot[data-slot="botas"]{top:236px;left:73px;width:44px;height:34px;border-radius:8px;}',
    '#vestuario{background:#1f1a1a;border-radius:10px;padding:14px;}',
    '.titulo-vestuario{margin:0 0 10px;font-size:1em;color:#e8c9a0;text-transform:uppercase;letter-spacing:.06em;}',
    '.estante{margin-bottom:14px;}',
    '.estante:last-child{margin-bottom:0;}',
    '.fila{list-style:none;margin:0;padding:0;display:flex;flex-wrap:wrap;gap:10px;justify-content:center;}',
    '.accesorio{background:#2a2222;border:2px solid #4a3a3a;border-radius:8px;padding:8px;',
    '  width:96px;text-align:center;font:inherit;color:inherit;cursor:default;}',
    '.miniatura{position:relative;width:64px;height:64px;margin:0 auto 6px;background:#3a2f2f;',
    '  border-radius:6px;overflow:hidden;}',
    '.miniatura img{width:100%;height:100%;object-fit:contain;display:block;}',
    '.miniatura.sin-imagen img{display:none;}',
    '.miniatura.sin-imagen::after{content:attr(data-nombre);position:absolute;inset:0;',
    '  display:flex;align-items:center;justify-content:center;text-align:center;',
    '  font-size:.68em;padding:4px;color:#c9b7ad;}',
    '.etiqueta{margin:0;font-size:.75em;line-height:1.25;}',
    '.ficha{display:block;margin-top:4px;font-size:.68em;color:#e8a05a;}',
    '[data-equipado="true"]{opacity:.4;position:relative;}',
    '[data-equipado="true"] .miniatura::before{content:"\\2713";position:absolute;inset:0;',
    '  display:flex;align-items:center;justify-content:center;font-size:1.6em;color:#8ce08c;',
    '  background:rgba(0,0,0,.45);z-index:1;}',
    '.esquina{margin-top:14px;padding:10px 14px;background:#241b1b;border-radius:8px;',
    '  display:flex;gap:18px;align-items:center;flex-wrap:wrap;font-size:.85em;color:#c9b7ad;}',
    '.consejo{margin-top:14px;padding:12px 14px;background:#241b1b;border-left:4px solid #e05a2b;',
    '  border-radius:0 8px 8px 0;font-size:.85em;}',
    '.consejo h3{margin:0 0 6px;font-size:1em;color:#e8c9a0;}',
    '.consejo a{color:#e8a05a;}',
    '.resaltado{outline:3px solid #ffd43b !important;outline-offset:2px;',
    '  box-shadow:0 0 12px rgba(255,212,59,.7) !important;}'
  ].join('\n');

  RL.gimnasioHTML = [
    '<!doctype html>',
    '<html>',
    '<head>',
    '<meta charset="utf-8">',
    '<title>Gimnasio</title>',
    '<style>' + ESTILOS_GIMNASIO + '</style>',
    '</head>',
    '<body>',
    '<main id="gimnasio">',

    '<section class="ring" id="ring">',
    '<p class="cartel">Elegí a tu peleador para empezar el entrenamiento</p>',
    '<div class="selector-genero" id="selector-genero">',
    '<div class="opcion-genero" role="button" tabindex="0" id="opcion-boxeador" data-genero="m"><span class="icono-genero">🥊</span><span class="nombre-opcion">Boxeador</span></div>',
    '<div class="opcion-genero" role="button" tabindex="0" id="opcion-boxeadora" data-genero="f"><span class="icono-genero">🥊</span><span class="nombre-opcion">Boxeadora</span></div>',
    '</div>',
    '<figure id="peleador" class="peleador" data-genero="">',
    '<div class="silueta-contenedor" data-nombre="Silueta del peleador">',
    '<img class="silueta" data-genero-img="m" src="img/boxeador.png" alt="Silueta del boxeador" onerror="this.parentElement.classList.add(\'sin-imagen\')">',
    '<img class="silueta" data-genero-img="f" src="img/boxeadora.png" alt="Silueta de la boxeadora" onerror="this.parentElement.classList.add(\'sin-imagen\')">',
    '<span class="slot" data-slot="casco" title="Casco"></span>',
    '<span class="slot" data-slot="bucal" title="Bucal"></span>',
    '<span class="slot" data-slot="venda-izq" title="Venda izquierda"></span>',
    '<span class="slot" data-slot="venda-der" title="Venda derecha"></span>',
    '<span class="slot" data-slot="guante-izq" title="Guante izquierdo"></span>',
    '<span class="slot" data-slot="guante-der" title="Guante derecho"></span>',
    '<span class="slot" data-slot="short" title="Short"></span>',
    '<span class="slot" data-slot="botas" title="Botas"></span>',
    '</div>',
    '</figure>',
    '</section>',

    '<section id="vestuario" aria-label="Vestuario">',
    '<h2 class="titulo-vestuario">Vestuario</h2>',

    '<div class="estante estante-cabeza" data-nivel="cabeza">',
    '<ul class="fila">',
    '<li id="casco-negro" class="accesorio casco" data-slot="casco" data-nombre="Casco" data-talle="58" data-tags="proteccion reglamentario" data-equipado="false">',
    '<div class="miniatura" data-nombre="Casco"><img src="img/cabezal.png" alt="Casco" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Casco</p>',
    '<a class="ficha" id="link-casco" href="https://www.ces.com.uy/casco">Ver ficha</a>',
    '</li>',
    '<button type="button" id="bucal-azul" class="accesorio bucal" data-slot="bucal" data-nombre="Bucal azul" data-equipado="false">',
    '<div class="miniatura" data-nombre="Bucal azul"><img src="img/bucal.png" alt="Bucal azul" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<span class="etiqueta">Bucal azul</span>',
    '</button>',
    '</ul>',
    '</div>',

    '<div class="estante estante-alto" data-nivel="manos">',
    '<ul class="fila">',
    '<li id="venda-izquierda" class="accesorio venda" data-slot="venda-izq" data-lado="izq" data-nombre="Venda izquierda" data-tags="algodon reglamentario" data-equipado="false">',
    '<div class="miniatura" data-nombre="Venda izquierda"><img src="img/venda-izq.png" alt="Venda izquierda" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Venda izquierda</p>',
    '</li>',
    '<li id="venda-derecha" class="accesorio venda" data-slot="venda-der" data-lado="der" data-nombre="Venda derecha" data-tags="algodon reglamentario" data-equipado="false">',
    '<div class="miniatura" data-nombre="Venda derecha"><img src="img/venda-der.png" alt="Venda derecha" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Venda derecha</p>',
    '</li>',
    '<li id="guante-izquierdo" class="accesorio guante reglamentario" data-slot="guante-izq" data-lado="izq" data-nombre="Guante izquierdo" data-talle="12oz" data-tags="cuero reglamentario" data-equipado="false">',
    '<div class="miniatura" data-nombre="Guante izquierdo"><img src="img/guante-izq.png" alt="Guante izquierdo" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Guante izquierdo</p>',
    '<a class="ficha" id="link-guante" href="https://guantes.tatf.com.uy">Ver ficha</a>',
    '</li>',
    '<li id="guante-derecho" class="accesorio guante practica" data-slot="guante-der" data-lado="der" data-nombre="Guante derecho" data-talle="12oz" data-tags="cuero practica" data-equipado="false">',
    '<div class="miniatura" data-nombre="Guante derecho"><img src="img/guante-der.png" alt="Guante derecho" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Guante derecho</p>',
    '</li>',
    '</ul>',
    '</div>',

    '<div class="estante estante-bajo" data-nivel="piernas">',
    '<ul class="fila">',
    '<li id="short-rojo" class="accesorio short" data-slot="short" data-nombre="Short" data-talle="m-largo" data-tags="satinado" data-equipado="false">',
    '<div class="miniatura" data-nombre="Short"><img src="img/short.png" alt="Short" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Short</p>',
    '</li>',
    '<li id="botas-altas" class="accesorio bota" data-slot="botas" data-nombre="Botas altas" data-talle="42" data-tags="cuero reglamentario" data-equipado="false">',
    '<div class="miniatura" data-nombre="Botas altas"><img src="img/botas.png" alt="Botas altas" onerror="this.parentElement.classList.add(\'sin-imagen\')"></div>',
    '<p class="etiqueta">Botas altas</p>',
    '<a class="ficha" id="link-botas" href="https://tienda-boxeo.example.com/botas">Ver ficha</a>',
    '</li>',
    '</ul>',
    '</div>',
    '</section>',

    '<div class="esquina" id="esquina">',
    '<span id="campana" class="campana">🔔 Campana</span>',
    '<p id="cartel-marca" class="cartel-marca" data-marca="CES">Academia CES</p>',
    '<small id="reloj" class="reloj" data-round="3">Round 3</small>',
    '<em id="mas-info" class="mas-info">Conocé la academia en ces.com.uy</em>',
    '</div>',

    '<aside id="consejo" class="consejo">',
    '<h3 id="titulo-consejo">Consejo del entrenador</h3>',
    '<div id="cuerpo-consejo" class="cuerpo-consejo">',
    '<p id="texto-consejo">Hidratate entre asalto y asalto.</p>',
    '</div>',
    '</aside>',

    '</main>',
    '</body>',
    '</html>'
  ].join('\n');
})();
